services:
  mysql:
    image: mysql:8.0
    container_name: mysql-spring
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"